-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgerhDQWUPmPHq/Kqv
mYSUbZa+6nxCKnpuVIT+ohUuZGegCgYIKoZIzj0DAQehRANCAAR0aYmzHALxLbmX
6Ra6I/ose43Y30QEuNRWKT5QMNeo11JyUK8n2KVFhfIAupAK2at7AqlfptmUad49
TzBY3Vx5
-----END PRIVATE KEY-----