using System.Collections.Generic;
using vnaisoft.common.Models;

namespace vnaisoft.common.Helpers
{
    public static class Constant
    {
        //public static readonly
        //        List<sys_common_group_model> list_loai_tai_san =
        //        new List<sys_common_group_model>{
        //            new sys_common_group_model(){ id ="1",name="Nhà cửa, vật kiến trúc",id_nhom="1" },
        //            new sys_common_group_model(){ id ="2",name="Máy móc, thiết bị",id_nhom="1" },
        //            new sys_common_group_model(){ id ="3",name="Phương tiện vận tải, truyền dẫn",id_nhom="1" },
        //            new sys_common_group_model(){ id ="4",name="Thiết bị, dụng cụ quản lý",id_nhom="1" },
        //            new sys_common_group_model(){ id ="5",name="Cây lâu năm, súc vật làm việc và cho sản phẩm",id_nhom="1" },
        //            new sys_common_group_model(){ id ="6",name="TSCĐ khác",id_nhom="1" },
        //            new sys_common_group_model(){ id ="7",name="TSCĐ hữu hình thuê tài chính",id_nhom="2" },
        //            new sys_common_group_model(){ id ="8",name="TSCĐ vô hình thuê tài chính",id_nhom="2" },
        //            new sys_common_group_model(){ id ="9",name="Quyền sử dụng đất",id_nhom="3" },
        //            new sys_common_group_model(){ id ="10",name="Quyền phát hành",id_nhom="3" },
        //            new sys_common_group_model(){ id ="11",name="Bản quyền, bằng sáng chế",id_nhom="3" },
        //            new sys_common_group_model(){ id ="12",name="Nhãn hiệu, tên thương mại",id_nhom="3" },
        //            new sys_common_group_model(){ id ="13",name="Chương trình phần mềm",id_nhom="3" },
        //            new sys_common_group_model(){ id ="14",name="Giấy phép và giấy phép nhượng quyền",id_nhom="3" },
        //            new sys_common_group_model(){ id ="15",name="TSCĐ vô hình khác",id_nhom="3" },


        //        };
        public static readonly
                List<erp_xuat_bao_cao_thue_sheet4_model> list_tai_khoan = new List<erp_xuat_bao_cao_thue_sheet4_model>()
            {
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="111", ten_tai_khoan= " Tiền mặt", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="1111", ten_tai_khoan= " Tiền Việt Nam", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="1112", ten_tai_khoan= " Ngoại tệ", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="112", ten_tai_khoan= "Tiền gửi Ngân hàng", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="1121", ten_tai_khoan= "Tiền Việt Nam", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="1122", ten_tai_khoan= "Ngoại tệ", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="121", ten_tai_khoan= "Chứng khoán kinh doanh", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="128", ten_tai_khoan= "Đầu tư nắm giữ đến ngày đáo hạn", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="1281", ten_tai_khoan= "Tiền gửi có kỳ hạn", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="1288", ten_tai_khoan= "Các khoản đầu tư khác nắm giữ đến ngày đáo hạn", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="131", ten_tai_khoan= "Phải thu của khách hàng", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="133", ten_tai_khoan= "Thuế GTGT được khấu trừ", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="1331", ten_tai_khoan= "Thuế GTGT được khấu trừ của hàng hóa, dịch vụ", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="1332", ten_tai_khoan= "Thuế GTGT được khấu trừ của TSCĐ", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="136", ten_tai_khoan= "Phải thu nội bộ", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="1361", ten_tai_khoan= "Vốn kinh doanh ở đơn vị trực thuộc", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="1368", ten_tai_khoan= "Phải thu nội bộ khác", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="138", ten_tai_khoan= "Phải thu khác", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="1381", ten_tai_khoan= "Tài sản thiếu chờ xử lý", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="1386", ten_tai_khoan= "Cầm cố, thế chấp, ký quỹ, ký cược", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="1388", ten_tai_khoan= "Phải thu khác", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="141", ten_tai_khoan= "Tạm ứng", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="151", ten_tai_khoan= "Hàng mua đang đi đường", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="152", ten_tai_khoan= "Nguyên liệu, vật liệu", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="153", ten_tai_khoan= "Công cụ, dụng cụ", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="154", ten_tai_khoan= "Chi phí sản xuất, kinh doanh dở dang", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="155", ten_tai_khoan= "Thành phẩm", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="156", ten_tai_khoan= "Hàng hóa", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="157", ten_tai_khoan= "Hàng gửi đi bán", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="211", ten_tai_khoan= "Tài sản cố định", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="2111", ten_tai_khoan= "TSCĐ hữu hình", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="2112", ten_tai_khoan= "TSCĐ thuê tài chính", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="2113", ten_tai_khoan= "TSCĐ vô hình", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="214", ten_tai_khoan= "Hao mòn tài sản cố định", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="2141", ten_tai_khoan= "Hao mòn TSCĐ hữu hình", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="2142", ten_tai_khoan= "Hao mòn TSCĐ thuê tài chính", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="2143", ten_tai_khoan= "Hao mòn TSCĐ vô hình", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="2147", ten_tai_khoan= "Hao mòn bất động sản đầu tư", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="217", ten_tai_khoan= "Bất động sản đầu tư", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="228", ten_tai_khoan= "Đầu tư góp vốn vào đơn vị khác", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="2281", ten_tai_khoan= "Đầu tư vào công ty liên doanh, liên kế", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="2288", ten_tai_khoan= "Đầu tư khác", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="229", ten_tai_khoan= "Dự phòng tổn thất tài sản", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="2291", ten_tai_khoan= "Dự phòng giảm giá chứng khoán kinh doanh", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="2292", ten_tai_khoan= "Dự phòng tổn thất đầu tư vào đơn vị khác", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="2293", ten_tai_khoan= "Dự phòng phải thu khó đòi", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="2294", ten_tai_khoan= "Dự phòng giảm giá hàng tồn kho", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="241", ten_tai_khoan= "Xây dựng cơ bản dở dang", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="2411", ten_tai_khoan= "Mua sắm TSCĐ", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="2412", ten_tai_khoan= "Xây dựng cơ bản", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="2413", ten_tai_khoan= "Sửa chữa lớn TSCĐ", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="242", ten_tai_khoan= "Chi phí trả trước", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
            };
        public static readonly
                List<erp_xuat_bao_cao_thue_sheet4_model> list_tai_khoan_no_phai_tra = new List<erp_xuat_bao_cao_thue_sheet4_model>()
            {
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="331", ten_tai_khoan= "Phải trả cho người bán", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="333", ten_tai_khoan= "Thuế và các khoản phải nộp Nhà nước", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="3331", ten_tai_khoan= "Thuế giá trị gia tăng phải nộp", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="33311", ten_tai_khoan= "Thuế GTGT đầu ra", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="33312", ten_tai_khoan= "Thuế GTGT hàng nhập khẩu", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="3332", ten_tai_khoan= "Thuế tiêu thụ đặc biệt", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="3333", ten_tai_khoan= "Thuế xuất, nhập khẩu", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="3334", ten_tai_khoan= "Thuế thu nhập doanh nghiệp", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="3335", ten_tai_khoan= "Thuế thu nhập cá nhân", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="3336", ten_tai_khoan= "Thuế tài nguyên", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="3337", ten_tai_khoan= "Thuế nhà đất, tiền thuê đất", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="3338", ten_tai_khoan= "Thuế bảo vệ môi trường và các loại thuế khác", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="33381", ten_tai_khoan= "Thuế bảo vệ môi trường", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="33382", ten_tai_khoan= "Các loại thuế khác", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="3339", ten_tai_khoan= "Phí, lệ phí và các khoản phải nộp khác", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="334", ten_tai_khoan= "Phải trả người lao động", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="335", ten_tai_khoan= "Chi phí phải trả", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="336", ten_tai_khoan= "Phải trả nội bộ", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="3361", ten_tai_khoan= "Phải trả nội bộ về vốn kinh doanh", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="3368", ten_tai_khoan= "Phải trả nội bộ khác", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="338", ten_tai_khoan= "Phải trả, phải nộp khác", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="3381", ten_tai_khoan= "Tài sản thừa chờ giải quyết", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="3382", ten_tai_khoan= "Kinh phí công đoàn", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="3383", ten_tai_khoan= "Bảo hiểm xã hội", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="3384", ten_tai_khoan= "Bảo hiểm y tế", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="3385", ten_tai_khoan= "Bảo hiểm thất nghiệp", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="3386", ten_tai_khoan= "Nhận ký quỹ, ký cược", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="3387", ten_tai_khoan= "Doanh thu chưa thực hiện", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="3388", ten_tai_khoan= "Phải trả, phải nộp khác", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="341", ten_tai_khoan= "Vay và nợ thuê tài chính", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="3411", ten_tai_khoan= "Các khoản đi vay", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="3412", ten_tai_khoan= "Nợ thuê tài chính", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="352", ten_tai_khoan= "Dự phòng phải trả", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="3521", ten_tai_khoan= "Dự phòng bảo hành sản phẩm hàng hóa", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="3522", ten_tai_khoan= "Dự phòng bảo hành công trình xây dựng ", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="3524", ten_tai_khoan= "Dự phòng phải trả khác", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="353", ten_tai_khoan= "Quỹ khen thưởng phúc lợi", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="3531", ten_tai_khoan= "Quỹ khen thưởng", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="3532", ten_tai_khoan= "Quỹ phúc lợi", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="3533", ten_tai_khoan= "Quỹ phúc lợi đã hình thành TSCĐ", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="3534", ten_tai_khoan= "Quỹ thưởng ban quản lý điều hành công ty", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="356", ten_tai_khoan= "Quỹ phát triển khoa học và công nghệ", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="3561", ten_tai_khoan= "Quỹ phát triển khoa học và công nghệ", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="3562", ten_tai_khoan= "Quỹ phát triển khoa học và công nghệ đã hình thành TSCĐ", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },

             };
        public static readonly
                List<erp_xuat_bao_cao_thue_sheet4_model> list_tai_khoan_von_chu_so_huu = new List<erp_xuat_bao_cao_thue_sheet4_model>()
            {
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="411", ten_tai_khoan= "Vốn đầu tư của chủ sở hữu", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="4111", ten_tai_khoan= "Vốn góp của chủ sở hữu", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="4112", ten_tai_khoan= "Thặng dư vốn cổ phần", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="4118", ten_tai_khoan= "Vốn khác", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="413", ten_tai_khoan= "Chênh lệch tỷ giá hối đoái", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="418", ten_tai_khoan= "Các quỹ thuộc vốn chủ sở hữu", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="419", ten_tai_khoan= "Cổ phiếu quỹ", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="421", ten_tai_khoan= "Lợi nhuận sau thuế chưa phân phối", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="4211", ten_tai_khoan= "Lợi nhuận sau thuế chưa phân phối năm trước", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="4212", ten_tai_khoan= "Lợi nhuận sau thuế chưa phân phối năm nay", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
             };
        public static readonly
                List<erp_xuat_bao_cao_thue_sheet4_model> list_tai_khoan_doanh_thu = new List<erp_xuat_bao_cao_thue_sheet4_model>()
            {
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="511", ten_tai_khoan= "Doanh thu bán hàng và cung cấp dịch vụ", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="5111", ten_tai_khoan= "Doanh thu bán hàng hóa", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="5112", ten_tai_khoan= "Doanh thu bán thành phẩm", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="5113", ten_tai_khoan= "Doanh thu cung cấp dịch vụ", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="5118", ten_tai_khoan= "Doanh thu khác", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="515", ten_tai_khoan= "Doanh thu hoạt động tài chính", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },

             };
        public static readonly
                List<erp_xuat_bao_cao_thue_sheet4_model> list_tai_khoan_sx_kd = new List<erp_xuat_bao_cao_thue_sheet4_model>()
            {
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="611", ten_tai_khoan= "Mua hàng", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="631", ten_tai_khoan= "Giá thành sản xuất", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="632", ten_tai_khoan= "Giá vốn hàng bán", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="635", ten_tai_khoan= "Chi phí tài chính", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="642", ten_tai_khoan= "Chi phí quản lý kinh doanh", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="6421", ten_tai_khoan= "Chi phí bán hàng", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="6422", ten_tai_khoan= "Chi phí quản lý doanh nghiệp", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },

             };
        public static readonly
                List<erp_xuat_bao_cao_thue_sheet4_model> list_tai_khoan_thu_nhap_khac = new List<erp_xuat_bao_cao_thue_sheet4_model>()
            {
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="711", ten_tai_khoan= "Thu nhập khác", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
            };
        public static readonly
                List<erp_xuat_bao_cao_thue_sheet4_model> list_tai_khoan_chi_phi_khac = new List<erp_xuat_bao_cao_thue_sheet4_model>()
            {
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="811", ten_tai_khoan= "Chi phí khác", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="821", ten_tai_khoan= "Chi phí thuế thu nhập doanh nghiệp", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
            };
        public static readonly
                List<erp_xuat_bao_cao_thue_sheet4_model> list_tai_khoan_kq_kd = new List<erp_xuat_bao_cao_thue_sheet4_model>()
            {
                new erp_xuat_bao_cao_thue_sheet4_model{ ma_tai_khoan="911", ten_tai_khoan= "Xác định kết quả kinh doanh", stDauKyNo = 0, stDauKyCo= 0, stPhatSinhNo = 0, stPhatSinhCo = 0, stCuoiKyNo = 0, stCuoiKyCo = 0 },
            };
        public static readonly
                List<erp_xuat_bao_cao_thue_sheet1_model> list_tai_san = new List<erp_xuat_bao_cao_thue_sheet1_model>()
            {
                new erp_xuat_bao_cao_thue_sheet1_model{ chi_tieu = "I. Tiền và các khoản tương đương tiền", ma_so = "110", thuyet_minh = "", so_cuoi_nam=1000000000, so_dau_nam=0},
                new erp_xuat_bao_cao_thue_sheet1_model{ chi_tieu = "II. Đầu tư tài chính", ma_so = "120", thuyet_minh = "", so_cuoi_nam=0, so_dau_nam=0},
                new erp_xuat_bao_cao_thue_sheet1_model{ chi_tieu = "1. Chứng khoán kinh doanh", ma_so = "121", thuyet_minh = "", so_cuoi_nam=0, so_dau_nam=0},
                new erp_xuat_bao_cao_thue_sheet1_model{ chi_tieu = "2. Đầu tư nắm giữ đến ngày đáo hạn", ma_so = "122", thuyet_minh = "", so_cuoi_nam=0, so_dau_nam=0},
                new erp_xuat_bao_cao_thue_sheet1_model{ chi_tieu = "3. Đầu tư góp vốn vào đơn vị khác", ma_so = "123", thuyet_minh = "", so_cuoi_nam=0, so_dau_nam=0},
                new erp_xuat_bao_cao_thue_sheet1_model{ chi_tieu = "4. Dự phòng tổn thất đầu tư tài chính (*)", ma_so = "124", thuyet_minh = "", so_cuoi_nam=0, so_dau_nam=0},
                new erp_xuat_bao_cao_thue_sheet1_model{ chi_tieu = " III. Các khoản phải thu", ma_so = "130", thuyet_minh = "", so_cuoi_nam=0, so_dau_nam=0},
                new erp_xuat_bao_cao_thue_sheet1_model{ chi_tieu = "1. Phải thu của khách hàng", ma_so = "131", thuyet_minh = "", so_cuoi_nam=0, so_dau_nam=0},
                new erp_xuat_bao_cao_thue_sheet1_model{ chi_tieu = "2. Trả trước cho người bán", ma_so = "132", thuyet_minh = "", so_cuoi_nam=0, so_dau_nam=0},
                new erp_xuat_bao_cao_thue_sheet1_model{ chi_tieu = "3. Vốn kinh doanh ở đơn vị trực thuộc", ma_so = "133", thuyet_minh = "", so_cuoi_nam=0, so_dau_nam=0},
                new erp_xuat_bao_cao_thue_sheet1_model{ chi_tieu = "4. Phải thu khác", ma_so = "134", thuyet_minh = "", so_cuoi_nam=0, so_dau_nam=0},
                new erp_xuat_bao_cao_thue_sheet1_model{ chi_tieu = "5. Tài sản thiếu chờ xử lý", ma_so = "135", thuyet_minh = "", so_cuoi_nam=0, so_dau_nam=0},
                new erp_xuat_bao_cao_thue_sheet1_model{ chi_tieu = "6. Dự phòng phải thu khó đòi (*)", ma_so = "136", thuyet_minh = "", so_cuoi_nam=0, so_dau_nam=0},
                new erp_xuat_bao_cao_thue_sheet1_model{ chi_tieu = "IV. Hàng tồn kho", ma_so = "140", thuyet_minh = "", so_cuoi_nam=0, so_dau_nam=0},
                new erp_xuat_bao_cao_thue_sheet1_model{ chi_tieu = "1. Hàng tồn kho", ma_so = "141", thuyet_minh = "", so_cuoi_nam=0, so_dau_nam=0},
                new erp_xuat_bao_cao_thue_sheet1_model{ chi_tieu = "2. Dự phòng giảm giả hàng tồn kho (*)", ma_so = "142", thuyet_minh = "", so_cuoi_nam=0, so_dau_nam=0},
                new erp_xuat_bao_cao_thue_sheet1_model{ chi_tieu = "V. Tài sản cố định", ma_so = "150", thuyet_minh = "", so_cuoi_nam=0, so_dau_nam=0},
                new erp_xuat_bao_cao_thue_sheet1_model{ chi_tieu = "- Nguyên giá", ma_so = "151", thuyet_minh = "", so_cuoi_nam=0, so_dau_nam=0},
                new erp_xuat_bao_cao_thue_sheet1_model{ chi_tieu = "- Giá trị hao mòn lũy kế (*)", ma_so = "152", thuyet_minh = "", so_cuoi_nam=0, so_dau_nam=0},
                new erp_xuat_bao_cao_thue_sheet1_model{ chi_tieu = "VI. Bất động sản đầu tư", ma_so = "160", thuyet_minh = "", so_cuoi_nam=0, so_dau_nam=0},
                new erp_xuat_bao_cao_thue_sheet1_model{ chi_tieu = "- Nguyên giá", ma_so = "161", thuyet_minh = "", so_cuoi_nam=0, so_dau_nam=0},
                new erp_xuat_bao_cao_thue_sheet1_model{ chi_tieu = "- Giá trị hao mòn lũy kế (*)", ma_so = "162", thuyet_minh = "", so_cuoi_nam=0, so_dau_nam=0},
                new erp_xuat_bao_cao_thue_sheet1_model{ chi_tieu = "VII. XDCB dở dang", ma_so = "170", thuyet_minh = "", so_cuoi_nam=0, so_dau_nam=0},
                new erp_xuat_bao_cao_thue_sheet1_model{ chi_tieu = "VIII. Tài sản khác", ma_so = "180", thuyet_minh = "", so_cuoi_nam=0, so_dau_nam=0},
                new erp_xuat_bao_cao_thue_sheet1_model{ chi_tieu = "1. Thuế GTGT được khấu trừ", ma_so = "181", thuyet_minh = "", so_cuoi_nam=0, so_dau_nam=0},
                new erp_xuat_bao_cao_thue_sheet1_model{ chi_tieu = "2. Tài sản khác", ma_so = "182", thuyet_minh = "", so_cuoi_nam=0, so_dau_nam=0},

            };
        public static readonly
            List<erp_xuat_bao_cao_thue_sheet1_model> list_nguon_von = new List<erp_xuat_bao_cao_thue_sheet1_model>()
            {
                new erp_xuat_bao_cao_thue_sheet1_model{ chi_tieu = "I. Nợ phải trả", ma_so = "300", thuyet_minh = "", so_cuoi_nam=0, so_dau_nam=0},
                new erp_xuat_bao_cao_thue_sheet1_model{ chi_tieu = "1. Phải trả người bán", ma_so = "311", thuyet_minh = "", so_cuoi_nam=0, so_dau_nam=0},
                new erp_xuat_bao_cao_thue_sheet1_model{ chi_tieu = "2. Người mua trả tiền trước", ma_so = "312", thuyet_minh = "", so_cuoi_nam=0, so_dau_nam=0},
                new erp_xuat_bao_cao_thue_sheet1_model { chi_tieu = "3. Thuế và các khoản phải nộp Nhà nước", ma_so = "313", thuyet_minh = "", so_cuoi_nam = 0, so_dau_nam = 0 },
                new erp_xuat_bao_cao_thue_sheet1_model { chi_tieu = "4. Phải trả người lao động", ma_so = "314", thuyet_minh = "", so_cuoi_nam = 0, so_dau_nam = 0 },
                new erp_xuat_bao_cao_thue_sheet1_model { chi_tieu = "5. Phải trả khác", ma_so = "315", thuyet_minh = "", so_cuoi_nam = 0, so_dau_nam = 0 },
                new erp_xuat_bao_cao_thue_sheet1_model { chi_tieu = "6. Vay và nợ thuê tài chính", ma_so = "316", thuyet_minh = "", so_cuoi_nam = 0, so_dau_nam = 0 },
                new erp_xuat_bao_cao_thue_sheet1_model { chi_tieu = "7. Phải trả nội bộ về vốn kinh doanh", ma_so = "317", thuyet_minh = "", so_cuoi_nam = 0, so_dau_nam = 0 },
                new erp_xuat_bao_cao_thue_sheet1_model { chi_tieu = "8. Dự phòng phải trả", ma_so = "318", thuyet_minh = "", so_cuoi_nam = 0, so_dau_nam = 0 },
                new erp_xuat_bao_cao_thue_sheet1_model { chi_tieu = "9. Quỹ khen thưởng, phúc lợi", ma_so = "319", thuyet_minh = "", so_cuoi_nam = 0, so_dau_nam = 0 },
                new erp_xuat_bao_cao_thue_sheet1_model { chi_tieu = "10. Quỹ phát triển khoa học và công nghệ", ma_so = "320", thuyet_minh = "", so_cuoi_nam = 0, so_dau_nam = 0 },
                new erp_xuat_bao_cao_thue_sheet1_model { chi_tieu = "II. Vốn chủ sở hữu", ma_so = "400", thuyet_minh = "", so_cuoi_nam = 1000000000, so_dau_nam = 0 },
                new erp_xuat_bao_cao_thue_sheet1_model { chi_tieu = "1. Vốn góp của chủ sở hữu", ma_so = "411", thuyet_minh = "", so_cuoi_nam = 1000000000, so_dau_nam = 0 },
                new erp_xuat_bao_cao_thue_sheet1_model { chi_tieu = "2. Thặng dư vốn cổ phần", ma_so = "412", thuyet_minh = "", so_cuoi_nam = 0, so_dau_nam = 0 },
                new erp_xuat_bao_cao_thue_sheet1_model { chi_tieu = "3. Vốn khác của chủ sở hữu", ma_so = "413", thuyet_minh = "", so_cuoi_nam = 0, so_dau_nam = 0 },
                new erp_xuat_bao_cao_thue_sheet1_model { chi_tieu = "4. Cổ phiếu quỹ (*)", ma_so = "414", thuyet_minh = "", so_cuoi_nam = 0, so_dau_nam = 0 },
                new erp_xuat_bao_cao_thue_sheet1_model { chi_tieu = "5. Chênh lệch tỷ giá hối đoái", ma_so = "415", thuyet_minh = "", so_cuoi_nam = 0, so_dau_nam = 0 },
                new erp_xuat_bao_cao_thue_sheet1_model { chi_tieu = "6. Các quỹ thuộc vốn chủ sở hữu", ma_so = "416", thuyet_minh = "", so_cuoi_nam = 0, so_dau_nam = 0 },
                new erp_xuat_bao_cao_thue_sheet1_model { chi_tieu = "7. Lợi nhuận sau thuế chưa phân phối", ma_so = "417", thuyet_minh = "", so_cuoi_nam = 0, so_dau_nam = 0 },
            };
        public static readonly
                List<sys_common_model> list_phuong_thuc_thanh_toan =
                new List<sys_common_model>{
                    new sys_common_model(){ id ="1",name="Tiền mặt" },
                    new sys_common_model(){ id ="2",name="Chuyển khoản" },
                    new sys_common_model(){ id ="3",name="Ví điện tử" },

                };
        public static readonly
    List<sys_common_model> list_nguon =
    new List<sys_common_model>{

            new sys_common_model(){ id ="1",name="Đơn hàng bán" },
             new sys_common_model(){ id ="2",name="Đơn hàng mua" },
                new sys_common_model(){ id ="3",name="Chuyển kho" },
              new sys_common_model(){ id ="4",name="Khác" },

    };
        public static readonly
        List<sys_common_model> list_vi_dien_tu =
        new List<sys_common_model>{
            new sys_common_model(){ id ="1",name="Momo" },
            new sys_common_model(){ id ="2",name="Zalopay" },
             new sys_common_model(){ id ="3",name="Payoo" },
            new sys_common_model(){ id ="4",name="Shopee_pay" },
             new sys_common_model(){ id ="5",name="Moca" },
        };
        public static readonly
        List<sys_common_ref_model> list_thuoc_tinh =
        new List<sys_common_ref_model>{
                    new sys_common_ref_model(){ id =1,name="Vật tư" },
                    new sys_common_ref_model(){ id =2,name="Thiết bị" },
                    new sys_common_ref_model(){ id =3,name="Bán thành phẩm" },
                    new sys_common_ref_model(){ id =4,name="Thành phẩm" },
                    new sys_common_ref_model(){ id =5,name="Hàng hóa" },
                    new sys_common_ref_model(){ id =6,name="Dịch vụ" },

        };
        public static readonly
        List<sys_common_ref_model> list_type_dac_tinh =
        new List<sys_common_ref_model>{
                    new sys_common_ref_model(){ id =1,name="Numeric" },
                    new sys_common_ref_model(){ id =2,name="String" },
                    new sys_common_ref_model(){ id =3,name="Datetime" },
                    new sys_common_ref_model(){ id =4,name="Select" },
                    new sys_common_ref_model(){ id =5,name="Mutiple Select" },

        };
        public static readonly
               List<sys_common_value_model> list_vat =
               new List<sys_common_value_model>{
                      new sys_common_value_model(){ id ="kct",name="Không chịu thuế" ,value= 0, },
                    new sys_common_value_model(){ id ="0",name="0%",value= 0, },
                    new sys_common_value_model(){ id ="5",name="5%" ,value= 5,},
                    new sys_common_value_model(){ id ="8",name="8%",value= 8, },
                    new sys_common_value_model(){ id ="10",name="10%",value= 10, },

               };
        public static readonly
            List<sys_common_model> listLoaiIn =
            new List<sys_common_model>{
                    new sys_common_model(){ id ="erp_don_hang_ban_le",name="Đơn hàng lẻ" },
                    new sys_common_model(){ id ="erp_don_hang_ban",name="Đơn hàng bán buôn/ bán sỉ" },
                    new sys_common_model(){ id ="erp_don_hang_mua",name="Đơn hàng mua" },
                    new sys_common_model(){ id ="erp_phieu_thu",name="Phiếu thu" },
                    new sys_common_model(){ id ="erp_phieu_chi",name="Phiếu chi" },
                    new sys_common_model(){ id ="erp_phieu_xuat_kho",name="Phiếu xuất kho" },
                     new sys_common_model(){ id ="erp_phieu_nhap_kho",name="Phiếu nhập" },
                      new sys_common_model(){ id ="erp_phieu_chuyen_kho",name="Phiểu chuyển kho" },
                     new sys_common_model(){ id ="kt_phieu_ke_toan",name="Phiểu kế toán" },
                     new sys_common_model(){ id ="kt_chung_tu_thu",name="Chứng từ thu" },
                    new sys_common_model(){ id ="kt_chung_tu_chi",name="Chứng từ chi" },
                    new sys_common_model(){ id ="kt_chung_tu_nhap",name="Chứng từ nhập" },
                    new sys_common_model(){ id ="kt_chung_tu_xuat",name="Chứng từ xuất" },
                           new sys_common_model(){ id ="kt_bang_tinh_tscd",name="Bảng tính tài sản cố định" },
                    new sys_common_model(){ id ="kt_bang_tinh_ccdc",name="Bảng tính công cụ dụng cụ" },


            };
     

        public static readonly
          List<sys_common_model> listLoaiChungTu =
          new List<sys_common_model>{
                    new sys_common_model(){ id ="erp_phieu_chi",name="Đơn hàng lẻ" },
                    new sys_common_model(){ id ="erp_phieu_thu",name="Đơn hàng bán buôn/ bán sỉ" },
                    new sys_common_model(){ id ="erp_phieu_nhap_kho",name="Đơn hàng mua" },
                    new sys_common_model(){ id ="erp_phieu_xuat_kho",name="Phiếu thu" },
                    new sys_common_model(){ id ="kt_bang_tinh_tscd",name="Phiếu chi" },
                    new sys_common_model(){ id ="kt_bang_tinh_ccdc",name="Phiếu xuất kho" },
                    new sys_common_model(){ id ="kt_chung_tu_thu",name="Phiếu nhập" },
                    new sys_common_model(){ id ="kt_chung_tu_chi",name="Phiểu chuyển kho" },
                    new sys_common_model(){ id ="kt_chung_tu_nhap",name="Phiểu kế toán" },
                    new sys_common_model(){ id ="kt_chung_tu_xuat",name="Phiểu kế toán" },
                     new sys_common_model(){ id ="kt_phieu_ke_toan",name="Phiểu kế toán" },



          };

        public static readonly
            List<sys_common_model> listLoaiMail =
            new List<sys_common_model>{
                    new sys_common_model(){ id ="1",name="Mail hệ thống"},
                    new sys_common_model(){ id ="2",name= "Mail dùng cho quy trình"},
            };
        public static readonly
            List<sys_select_common_group_model> list_loai_tai_san =
            new List<sys_select_common_group_model>{
                    new sys_select_common_group_model()
                    { id= "2",
                      name= "Tài sản cố định hữu hình",
                      listData=new List<sys_common_model>{
                            new sys_common_model() { id= "21", name= "Máy móc, thiết bị", id_parent = "2" },
                            new sys_common_model() { id= "22", name= "Phương tiện vận tải, truyền dẫn", id_parent = "2" },
                            new sys_common_model() { id= "23", name= "Thiết bị, dụng cụ quản lý" , id_parent = "2"},
                            new sys_common_model() { id= "24", name= "Cây lâu năm, súc vật làm việc và cho sản phẩm", id_parent = "2" },
                            new sys_common_model() { id= "25", name= "TSCĐ khác" },
                        }
                    },
                    new sys_select_common_group_model()
                    { id= "3",
                      name= "Tài sản cố định thuê tài chính",
                      listData=new List<sys_common_model>{
                            new sys_common_model() { id= "31", name= "TSCĐ hữu hình thuê tài chính.", id_parent = "3" },
                            new sys_common_model() { id= "32", name= "TSCĐ vô hình thuê tài chính.", id_parent = "3" },

                        }
                    },
                    new sys_select_common_group_model()
                    { id= "4",
                      name= "Tài sản cố định vô hình",
                      listData=new List<sys_common_model>{
                            new sys_common_model(){ id= "41", name= "Quyền sử dụng đất", id_parent = "4" },
                            new sys_common_model(){ id= "42", name= "Quyền phát hành", id_parent = "4" },
                            new sys_common_model(){ id= "43", name= "Bản quyền, bằng sáng chế" , id_parent = "4"},
                            new sys_common_model(){ id= "44", name= "Nhãn hiệu, tên thương mại", id_parent = "4" },
                            new sys_common_model(){ id= "45", name= "Chương trình phần mềm" , id_parent = "4"},
                            new sys_common_model(){ id= "46", name= "Giấy phép và giấy phép nhượng quyền" , id_parent = "4"},
                            new sys_common_model(){ id= "47", name= "TSCĐ vô hình khác", id_parent = "4" }
                        }
                    },

                      new sys_select_common_group_model()
                    { id= "1",
                      name= "Công cụ dụng cụ",
                      listData=new List<sys_common_model>{
                            new sys_common_model(){ id= "11", name= "Công cụ, dụng cụ",id_parent="1" },
                            new sys_common_model(){ id= "12", name= "Bao bì luân chuyển" ,id_parent="1"},
                            new sys_common_model(){ id= "13", name= "Đồ dùng cho thuê" ,id_parent="1"},
                            new sys_common_model(){ id= "14", name= "Thiết bị, phụ tùng thay thế",id_parent="1" },
                            new sys_common_model(){ id= "15", name= "Khác",id_parent="1" },


                        }
                    },


            };

        public static readonly
               List<sys_common_model> listbank =
               new List<sys_common_model>{
                    new sys_common_model() {name= "Ngân hàng TMCP Đầu tư và Phát triển Việt Nam",name_en= "Joint Stock Commercial Bank for Investment and Development of Vietnam",id= "BIDV"},
                    new sys_common_model() {name= "Ngân hàng TMCP Công thương Việt Nam",name_en= "Vietnam Joint Stock Commercial Bank of Industry and Trade",id= "VietinBank"},
                    new sys_common_model() {name= "Ngân hàng TMCP Ngoại Thương Việt Nam",name_en= "Joint Stock Commercial Bank for Foreign Trade of Vietnam",id= "Vietcombank"},
                    new sys_common_model() {name= "Ngân hàng TMCP Việt Nam Thịnh Vượng",name_en= "Vietnam Commercial Joint Stock Bank for Private Enterprise",id= "VPBank"},
                    new sys_common_model() {name= "Ngân hàng TMCP Quân Đội",name_en= "Military Commercial Joint Stock Bank",id= "MB"},
                    new sys_common_model() {name= "Ngân hàng TMCP Kỹ Thương",name_en= "Vietnam Technological and Commercial Joint Stock Bank",id= "Techcombank"},
                    new sys_common_model() {name= "Ngân hàng NN&PT Nông thôn Việt Nam",name_en= "Vietnam Bank for Agriculture and Rural Development",id= "Agribank"},
                    new sys_common_model() {name= "Ngân hàng TMCP Á Châu",name_en= "Asia Commercial Joint Stock Bank",id= "ACB"},
                    new sys_common_model() {name= "Ngân hàng TMCP Phát triển Thành phố Hồ Chí Minh",name_en= "Ho Chi Minh city Development Joint Stock Commercial Bank",id= "HDBank"},
                    new sys_common_model() {name= "Ngân hàng TMCP Sài Gòn – Hà Nội",name_en= "Saigon-Hanoi Commercial Joint Stock Bank",id= "SHB"},
                    new sys_common_model() {name= "Ngân hàng TMCP Sài Gòn Thương Tín",name_en= "Saigon Thuong Tin Commercial Joint Stock Bank",id= "Sacombank"},
                    new sys_common_model() {name= "Ngân hàng Chính sách xã hội Việt Nam",name_en= "Vietnam Bank for Social Policies",id= "VBSP"},
                    new sys_common_model() {name= "Ngân hàng TMCP Quốc Tế Vietnam",name_en= "International Commercial Joint Stock Bank",id= "VIB"},
                    new sys_common_model() {name= "Ngân hàng TMCP Hàng Hải",name_en= "The Maritime Commercial Joint Stock Bank",id= "MSB"},
                    new sys_common_model() {name= "Ngân hàng TMCP Sài Gòn",name_en= "Sai Gon Commercial Joint Stock Bank",id= "SCB"},
                    new sys_common_model() {name= "Ngân hàng Phát triển Việt Nam",name_en= "Vietnam Development Bank",id= "VDB"},
                    new sys_common_model() {name= "Ngân hàng TMCP Đông Nam Á",name_en= "Southeast Asia Commercial Joint Stock Bank",id= "SeABank"},
                    new sys_common_model() {name= "Ngân hàng TMCP Phương Đông",name_en= "Orient Commercial Joint Stock Bank",id= "OCB"},
                    new sys_common_model() {name= "Ngân hàng TMCP Xuất Nhập Khẩu",name_en= "Vietnam Export Import Commercial Joint Stock",id= "Eximbank"},
                    new sys_common_model() {name= "Ngân hàng TMCP Bưu điện Liên Việt",name_en= "LienViet Commercial Joint Stock Bank",id= "LienVietPostBank"},
                    new sys_common_model() {name= "Ngân hàng TMCP Tiên Phong",name_en= "TienPhong Commercial Joint Stock Bank",id= "TPBank"},
                    new sys_common_model() {name= "Ngân hàng TMCP Đại Chúng Việt Nam",name_en= "Public Vietnam Bank",id= "PVcomBank"},
                    new sys_common_model() {name= "Ngân hàng TNHH MTV Woori Việt Nam",name_en= "Woori Bank Vietnam Limited",id= "Woori"},
                    new sys_common_model() {name= "Ngân hàng TMCP Bắc Á",name_en= "BAC A Commercial Joint Stock Bank",id= "Bac A Bank"},
                    new sys_common_model() {name= "Ngân hàng TNHH MTV HSBC Việt Nam",name_en= "HSBC Bank Vietnam Limited",id= "HSBC"},
                    new sys_common_model() {name= "Ngân hàng TNHH MTV Standard Chartered Việt Nam",name_en= "Standard Chartered Bank Vietnam Limited",id= "SCBVL"},
                    new sys_common_model() {name= "Ngân hàng TNHH MTV Public Bank Việt Nam",name_en= "Public Bank Vietnam Limited",id= "PBVN"},
                    new sys_common_model() {name= "Ngân hàng TMCP An Bình",name_en= "An Binh Commercial Joint Stock Bank",id= "ABBANK"},
                    new sys_common_model() {name= "Ngân hàng TNHH MTV Shinhan Việt Nam",name_en= "Shinhan Bank Vietnam Limited",id= "SHBVN"},
                    new sys_common_model() {name= "Ngân hàng TMCP Việt Á",name_en= "Viet A Commercial Joint Stock Bank",id= "VietABank"},
                    new sys_common_model() {name= "Ngân hàng TMCP Đông Á",name_en= "DONG A Commercial Joint Stock Bank",id= "DongA Bank"},
                    new sys_common_model() {name= "Ngân hàng TNHH MTV UOB Việt Nam",name_en= "UOB Vietnam Limited",id= "UOB"},
                    new sys_common_model() {name= "Ngân hàng TMCP Việt Nam Thương Tín",name_en= "Vietnam Thuong Tin Commercial Joint Stock Bank",id= "Vietbank"},
                    new sys_common_model() {name= "Ngân hàng TMCP Nam Á",name_en= "Nam A Commercial Joint Stock Bank",id= "Nam A Bank"},
                    new sys_common_model() {name= "Ngân hàng TMCP Quốc dân",name_en= "National Citizen bank",id= "NCB"},
                    new sys_common_model() {name= "Ngân hàng TNHH MTV Đại Dương",name_en= "Ocean Commercial One Member Limited Liability Bank",id= "OceanBank"},
                    new sys_common_model() {name= "Ngân hàng TNHH MTV CIMB Việt Nam",name_en= "CIMB Bank Vietnam Limited",id= "CIMB"},
                    new sys_common_model() {name= "Ngân hàng TMCP Bản Việt",name_en= "Viet Capital Commercial Joint Stock Bank",id= "Viet Capital Bank"},
                    new sys_common_model() {name= "Ngân hàng TMCP Kiên Long",name_en= "Kien Long Commercial Joint Stock Bank",id= "Kienlongbank"},
                    new sys_common_model() {name= "Ngân hàng TNHH Indovina",name_en= "Indovina Bank Ltd.",id= "IVB"},
                    new sys_common_model() {name= "Ngân hàng TMCP Bảo Việt",name_en= "Bao Viet Joint Stock commercial Bank",id= "BAOVIET Bank"},
                    new sys_common_model() {name= "Ngân hàng TMCP Sài Gòn Công Thương",name_en= "Saigon Bank for Industry & Trade",id= "SAIGONBANK"},
                    new sys_common_model() {name= "Ngân hàng Hợp tác xã Việt Nam",name_en= "Co-operative bank of VietNam",id= "Co-opBank"},
                    new sys_common_model() {name= "Ngân hàng TNHH MTV Dầu khí toàn cầu",name_en= "Global Petro Sole Member Limited Commercial Bank",id= "GPBank"},
                    new sys_common_model() {name= "Ngân hàng Liên doanh Việt Nga",name_en= "Vietnam Russia Joint Venture Bank",id= "VRB"},
                    new sys_common_model() {name= "Ngân hàng TNHH MTV Xây dựng",name_en= "Construction Commercial One Member Limited Liability Bank",id= "CB"},
                    new sys_common_model() {name= "Ngân hàng TMCP Xăng dầu Petrolimex",name_en= "Petrolimex Group Commercial Joint Stock Bank",id= "PG Bank"},
                    new sys_common_model() {name= "Ngân hàng TNHH MTV ANZ Việt Nam",name_en= "ANZ Bank Vietnam Limited",id= "ANZVL"},
                    new sys_common_model() {name= "Ngân hàng TNHH MTV Hong Leong Việt Nam",name_en= "Hong Leong Bank Vietnam Limited",id= "HLBVN" }

               };
        public static readonly
               List<sys_common_model> list_tien_te =
               new List<sys_common_model>{
                    new sys_common_model(){ name= "US Dollar", id= "USD", },
                    new sys_common_model(){ name= "Canadian Dollar", id= "CAD", },
                    new sys_common_model(){ name= "Euro", id= "EUR", },
                    new sys_common_model(){ name= "United Arab Emirates Dirham", id= "AED", },
                    new sys_common_model(){ name= "Afghan Afghani", id= "AFN", },
                    new sys_common_model(){ name= "Albanian Lek", id= "ALL", },
                    new sys_common_model(){ name= "Armenian Dram", id= "AMD", },
                    new sys_common_model(){ name= "Argentine Peso", id= "ARS", },
                    new sys_common_model(){ name= "Australian Dollar", id= "AUD", },
                    new sys_common_model(){ name= "Azerbaijani Manat", id= "AZN", },
                    new sys_common_model(){ name= "Bosnia-Herzegovina Convertible Mark", id= "BAM", },
                    new sys_common_model(){ name= "Bangladeshi Taka", id= "BDT", },
                    new sys_common_model(){ name= "Bulgarian Lev", id= "BGN", },
                    new sys_common_model(){ name= "Bahraini Dinar", id= "BHD", },
                    new sys_common_model(){ name= "Burundian Franc", id= "BIF", },
                    new sys_common_model(){ name= "Brunei Dollar", id= "BND", },
                    new sys_common_model(){ name= "Bolivian Boliviano", id= "BOB", },
                    new sys_common_model(){ name= "Brazilian Real", id= "BRL", },
                    new sys_common_model(){ name= "Botswanan Pula", id= "BWP", },
                    new sys_common_model(){ name= "Belarusian Ruble", id= "BYN", },
                    new sys_common_model(){ name= "Belize Dollar", id= "BZD", },
                    new sys_common_model(){ name= "Congolese Franc", id= "CDF", },
                    new sys_common_model(){ name= "Swiss Franc", id= "CHF", },
                    new sys_common_model(){ name= "Chilean Peso", id= "CLP", },
                    new sys_common_model(){ name= "Chinese Yuan", id= "CNY", },
                    new sys_common_model(){ name= "Colombian Peso", id= "COP", },
                    new sys_common_model(){ name= "Costa Rican Colón", id= "CRC", },
                    new sys_common_model(){ name= "Cape Verdean Escudo", id= "CVE", },
                    new sys_common_model(){ name= "Czech Republic Koruna", id= "CZK", },
                    new sys_common_model(){ name= "Djiboutian Franc", id= "DJF", },
                    new sys_common_model(){ name= "Danish Krone", id= "DKK", },
                    new sys_common_model(){ name= "Dominican Peso", id= "DOP", },
                    new sys_common_model(){ name= "Algerian Dinar", id= "DZD", },
                    new sys_common_model(){ name= "Estonian Kroon", id= "EEK", },
                    new sys_common_model(){ name= "Egyptian Pound", id= "EGP", },
                    new sys_common_model(){ name= "Eritrean Nakfa", id= "ERN", },
                    new sys_common_model(){ name= "Ethiopian Birr", id= "ETB", },
                    new sys_common_model(){ name= "British Pound Sterling", id= "GBP", },
                    new sys_common_model(){ name= "Georgian Lari", id= "GEL", },
                    new sys_common_model(){ name= "Ghanaian Cedi", id= "GHS", },
                    new sys_common_model(){ name= "Guinean Franc", id= "GNF", },
                    new sys_common_model(){ name= "Guatemalan Quetzal", id= "GTQ", },
                    new sys_common_model(){ name= "Hong Kong Dollar", id= "HKD", },
                    new sys_common_model(){ name= "Honduran Lempira", id= "HNL", },
                    new sys_common_model(){ name= "Croatian Kuna", id= "HRK", },
                    new sys_common_model(){ name= "Hungarian Forint", id= "HUF", },
                    new sys_common_model(){ name= "Indonesian Rupiah", id= "IDR", },
                    new sys_common_model(){ name= "Israeli New Sheqel", id= "ILS", },
                    new sys_common_model(){ name= "Indian Rupee", id= "INR", },
                    new sys_common_model(){ name= "Iraqi Dinar", id= "IQD", },
                    new sys_common_model(){ name= "Iranian Rial", id= "IRR", },
                    new sys_common_model(){ name= "Icelandic Króna", id= "ISK", },
                    new sys_common_model(){ name= "Jamaican Dollar", id= "JMD", },
                    new sys_common_model(){ name= "Jordanian Dinar", id= "JOD", },
                    new sys_common_model(){ name= "Japanese Yen", id= "JPY", },
                    new sys_common_model(){ name= "Kenyan Shilling", id= "KES", },
                    new sys_common_model(){ name= "Cambodian Riel", id= "KHR", },
                    new sys_common_model(){ name= "Comorian Franc", id= "KMF", },
                    new sys_common_model(){ name= "South Korean Won", id= "KRW", },
                    new sys_common_model(){ name= "Kuwaiti Dinar", id= "KWD", },
                    new sys_common_model(){ name= "Kazakhstani Tenge", id= "KZT", },
                    new sys_common_model(){ name= "Lebanese Pound", id= "LBP", },
                    new sys_common_model(){ name= "Sri Lankan Rupee", id= "LKR", },
                    new sys_common_model(){ name= "Lithuanian Litas", id= "LTL", },
                    new sys_common_model(){ name= "Latvian Lats", id= "LVL", },
                    new sys_common_model(){ name= "Libyan Dinar", id= "LYD", },
                    new sys_common_model(){ name= "Moroccan Dirham", id= "MAD", },
                    new sys_common_model(){ name= "Moldovan Leu", id= "MDL", },
                    new sys_common_model(){ name= "Malagasy Ariary", id= "MGA", },
                    new sys_common_model(){ name= "Macedonian Denar", id= "MKD", },
                    new sys_common_model(){ name= "Myanma Kyat", id= "MMK", },
                    new sys_common_model(){ name= "Macanese Pataca", id= "MOP", },
                    new sys_common_model(){ name= "Mauritian Rupee", id= "MUR", },
                    new sys_common_model(){ name= "Mexican Peso", id= "MXN", },
                    new sys_common_model(){ name= "Malaysian Ringgit", id= "MYR", },
                    new sys_common_model(){ name= "Mozambican Metical", id= "MZN", },
                    new sys_common_model(){ name= "Namibian Dollar", id= "NAD", },
                    new sys_common_model(){ name= "Nigerian Naira", id= "NGN", },
                    new sys_common_model(){ name= "Nicaraguan Córdoba", id= "NIO", },
                    new sys_common_model(){ name= "Norwegian Krone", id= "NOK", },
                    new sys_common_model(){ name= "Nepalese Rupee", id= "NPR", },
                    new sys_common_model(){ name= "New Zealand Dollar", id= "NZD", },
                    new sys_common_model(){ name= "Omani Rial", id= "OMR", },
                    new sys_common_model(){ name= "Panamanian Balboa", id= "PAB", },
                    new sys_common_model(){ name= "Peruvian Nuevo Sol", id= "PEN", },
                    new sys_common_model(){ name= "Philippine Peso", id= "PHP", },
                    new sys_common_model(){ name= "Pakistani Rupee", id= "PKR", },
                    new sys_common_model(){ name= "Polish Zloty", id= "PLN", },
                    new sys_common_model(){ name= "Paraguayan Guarani", id= "PYG", },
                    new sys_common_model(){ name= "Qatari Rial", id= "QAR", },
                    new sys_common_model(){ name= "Romanian Leu", id= "RON", },
                    new sys_common_model(){ name= "Serbian Dinar", id= "RSD", },
                    new sys_common_model(){ name= "Russian Ruble", id= "RUB", },
                    new sys_common_model(){ name= "Rwandan Franc", id= "RWF", },
                    new sys_common_model(){ name= "Saudi Riyal", id= "SAR", },
                    new sys_common_model(){ name= "Sudanese Pound", id= "SDG", },
                    new sys_common_model(){ name= "Swedish Krona", id= "SEK", },
                    new sys_common_model(){ name= "Singapore Dollar", id= "SGD", },
                    new sys_common_model(){ name= "Somali Shilling", id= "SOS", },
                    new sys_common_model(){ name= "Syrian Pound", id= "SYP", },
                    new sys_common_model(){ name= "Thai Baht", id= "THB", },
                    new sys_common_model(){ name= "Tunisian Dinar", id= "TND", },
                    new sys_common_model(){ name= "Tongan Paʻanga", id= "TOP", },
                    new sys_common_model(){ name= "Turkish Lira", id= "TRY", },
                    new sys_common_model(){ name= "Trinidad and Tobago Dollar", id= "TTD", },
                    new sys_common_model(){ name= "New Taiwan Dollar", id= "TWD", },
                    new sys_common_model(){ name= "Tanzanian Shilling", id= "TZS", },
                    new sys_common_model(){ name= "Ukrainian Hryvnia", id= "UAH", },
                    new sys_common_model(){ name= "Ugandan Shilling", id= "UGX", },
                    new sys_common_model(){ name= "Uruguayan Peso", id= "UYU", },
                    new sys_common_model(){ name= "Uzbekistan Som", id= "UZS", },
                    new sys_common_model(){ name= "Venezuelan Bolívar", id= "VEF", },
                    new sys_common_model(){ name= "Vietnamese Dong", id= "VND", },
                    new sys_common_model(){ name= "CFA Franc BEAC", id= "XAF", },
                    new sys_common_model(){ name= "CFA Franc BCEAO", id= "XOF", },
                    new sys_common_model(){ name= "Yemeni Rial", id= "YER", },
                    new sys_common_model(){ name= "South African Rand", id= "ZAR", },
                    new sys_common_model(){ name= "Zambian Kwacha", id= "ZMK", },
                    new sys_common_model(){ name= "Zimbabwean Dollar", id= "ZWL", }
               };
        public static readonly
               List<sys_common_model> listCountry =
               new List<sys_common_model>{
                 new sys_common_model(){ name= "Afghanistan", id= "AF" },
                 new sys_common_model(){ name= "land Islands", id= "AX" },
                 new sys_common_model(){ name= "Albania", id= "AL" },
                 new sys_common_model(){ name= "Algeria", id= "DZ" },
                 new sys_common_model(){ name= "American Samoa", id= "AS" },
                 new sys_common_model(){ name= "AndorrA", id= "AD" },
                 new sys_common_model(){ name= "Angola", id= "AO" },
                 new sys_common_model(){ name= "Anguilla", id= "AI" },
                 new sys_common_model(){ name= "Antarctica", id= "AQ" },
                 new sys_common_model(){ name= "Antigua and Barbuda", id= "AG" },
                 new sys_common_model(){ name= "Argentina", id= "AR" },
                 new sys_common_model(){ name= "Armenia", id= "AM" },
                 new sys_common_model(){ name= "Aruba", id= "AW" },
                 new sys_common_model(){ name= "Australia", id= "AU" },
                 new sys_common_model(){ name= "Austria", id= "AT" },
                 new sys_common_model(){ name= "Azerbaijan", id= "AZ" },
                 new sys_common_model(){ name= "Bahamas", id= "BS" },
                 new sys_common_model(){ name= "Bahrain", id= "BH" },
                 new sys_common_model(){ name= "Bangladesh", id= "BD" },
                 new sys_common_model(){ name= "Barbados", id= "BB" },
                 new sys_common_model(){ name= "Belarus", id= "BY" },
                 new sys_common_model(){ name= "Belgium", id= "BE" },
                 new sys_common_model(){ name= "Belize", id= "BZ" },
                 new sys_common_model(){ name= "Benin", id= "BJ" },
                 new sys_common_model(){ name= "Bermuda", id= "BM" },
                 new sys_common_model(){ name= "Bhutan", id= "BT" },
                 new sys_common_model(){ name= "Bolivia", id= "BO" },
                 new sys_common_model(){ name= "Bosnia and Herzegovina", id= "BA" },
                 new sys_common_model(){ name= "Botswana", id= "BW" },
                 new sys_common_model(){ name= "Bouvet Island", id= "BV" },
                 new sys_common_model(){ name= "Brazil", id= "BR" },
                 new sys_common_model(){ name= "British Indian Ocean Territory", id= "IO" },
                 new sys_common_model(){ name= "Brunei Darussalam", id= "BN" },
                 new sys_common_model(){ name= "Bulgaria", id= "BG" },
                 new sys_common_model(){ name= "Burkina Faso", id= "BF" },
                 new sys_common_model(){ name= "Burundi", id= "BI" },
                 new sys_common_model(){ name= "Cambodia", id= "KH" },
                 new sys_common_model(){ name= "Cameroon", id= "CM" },
                 new sys_common_model(){ name= "Canada", id= "CA" },
                 new sys_common_model(){ name= "Cape Verde", id= "CV" },
                 new sys_common_model(){ name= "Cayman Islands", id= "KY" },
                 new sys_common_model(){ name= "Central African Republic", id= "CF" },
                 new sys_common_model(){ name= "Chad", id= "TD" },
                 new sys_common_model(){ name= "Chile", id= "CL" },
                 new sys_common_model(){ name= "China", id= "CN" },
                 new sys_common_model(){ name= "Christmas Island", id= "CX" },
                 new sys_common_model(){ name= "Cocos (Keeling) Islands", id= "CC" },
                 new sys_common_model(){ name= "Colombia", id= "CO" },
                 new sys_common_model(){ name= "Comoros", id= "KM" },
                 new sys_common_model(){ name= "Congo", id= "CG" },
                 new sys_common_model(){ name= "Congo, The Democratic Republic of the", id= "CD" },
                 new sys_common_model(){ name= "Cook Islands", id= "CK" },
                 new sys_common_model(){ name= "Costa Rica", id= "CR" },
                 new sys_common_model(){ name= "Cote D\"Ivoire", id= "CI" },
                 new sys_common_model(){ name= "Croatia", id= "HR" },
                 new sys_common_model(){ name= "Cuba", id= "CU" },
                 new sys_common_model(){ name= "Cyprus", id= "CY" },
                 new sys_common_model(){ name= "Czech Republic", id= "CZ" },
                 new sys_common_model(){ name= "Denmark", id= "DK" },
                 new sys_common_model(){ name= "Djibouti", id= "DJ" },
                 new sys_common_model(){ name= "Dominica", id= "DM" },
                 new sys_common_model(){ name= "Dominican Republic", id= "DO" },
                 new sys_common_model(){ name= "Ecuador", id= "EC" },
                 new sys_common_model(){ name= "Egypt", id= "EG" },
                 new sys_common_model(){ name= "El Salvador", id= "SV" },
                 new sys_common_model(){ name= "Equatorial Guinea", id= "GQ" },
                 new sys_common_model(){ name= "Eritrea", id= "ER" },
                 new sys_common_model(){ name= "Estonia", id= "EE" },
                 new sys_common_model(){ name= "Ethiopia", id= "ET" },
                 new sys_common_model(){ name= "Falkland Islands (Malvinas)", id= "FK" },
                 new sys_common_model(){ name= "Faroe Islands", id= "FO" },
                 new sys_common_model(){ name= "Fiji", id= "FJ" },
                 new sys_common_model(){ name= "Finland", id= "FI" },
                 new sys_common_model(){ name= "France", id= "FR" },
                 new sys_common_model(){ name= "French Guiana", id= "GF" },
                 new sys_common_model(){ name= "French Polynesia", id= "PF" },
                 new sys_common_model(){ name= "French Southern Territories", id= "TF" },
                 new sys_common_model(){ name= "Gabon", id= "GA" },
                 new sys_common_model(){ name= "Gambia", id= "GM" },
                 new sys_common_model(){ name= "Georgia", id= "GE" },
                 new sys_common_model(){ name= "Germany", id= "DE" },
                 new sys_common_model(){ name= "Ghana", id= "GH" },
                 new sys_common_model(){ name= "Gibraltar", id= "GI" },
                 new sys_common_model(){ name= "Greece", id= "GR" },
                 new sys_common_model(){ name= "Greenland", id= "GL" },
                 new sys_common_model(){ name= "Grenada", id= "GD" },
                 new sys_common_model(){ name= "Guadeloupe", id= "GP" },
                 new sys_common_model(){ name= "Guam", id= "GU" },
                 new sys_common_model(){ name= "Guatemala", id= "GT" },
                 new sys_common_model(){ name= "Guernsey", id= "GG" },
                 new sys_common_model(){ name= "Guinea", id= "GN" },
                 new sys_common_model(){ name= "Guinea-Bissau", id= "GW" },
                 new sys_common_model(){ name= "Guyana", id= "GY" },
                 new sys_common_model(){ name= "Haiti", id= "HT" },
                 new sys_common_model(){ name= "Heard Island and Mcdonald Islands", id= "HM" },
                 new sys_common_model(){ name= "Holy See (Vatican City State)", id= "VA" },
                 new sys_common_model(){ name= "Honduras", id= "HN" },
                 new sys_common_model(){ name= "Hong Kong", id= "HK" },
                 new sys_common_model(){ name= "Hungary", id= "HU" },
                 new sys_common_model(){ name= "Iceland", id= "IS" },
                 new sys_common_model(){ name= "India", id= "IN" },
                 new sys_common_model(){ name= "Indonesia", id="ID" },
                 new sys_common_model(){ name= "Iran, Islamic Republic Of", id= "IR" },
                 new sys_common_model(){ name= "Iraq", id= "IQ" },
                 new sys_common_model(){ name= "Ireland", id= "IE" },
                 new sys_common_model(){ name= "Isle of Man", id= "IM" },
                 new sys_common_model(){ name= "Israel", id= "IL" },
                 new sys_common_model(){ name= "Italy", id= "IT" },
                 new sys_common_model(){ name= "Jamaica", id= "JM" },
                 new sys_common_model(){ name= "Japan", id= "JP" },
                 new sys_common_model(){ name= "Jersey", id= "JE" },
                 new sys_common_model(){ name= "Jordan", id= "JO" },
                 new sys_common_model(){ name= "Kazakhstan", id= "KZ" },
                 new sys_common_model(){ name= "Kenya", id= "KE" },
                 new sys_common_model(){ name= "Kiribati", id= "KI" },
                 new sys_common_model(){ name= "Korea, Democratic People\"S Republic of", id= "KP" },
                 new sys_common_model(){ name= "Korea, Republic of", id= "KR" },
                 new sys_common_model(){ name= "Kuwait", id= "KW" },
                 new sys_common_model(){ name= "Kyrgyzstan", id= "KG" },
                 new sys_common_model(){ name= "Lao People\"S Democratic Republic", id= "LA" },
                 new sys_common_model(){ name= "Latvia", id= "LV" },
                 new sys_common_model(){ name= "Lebanon", id= "LB" },
                 new sys_common_model(){ name= "Lesotho", id= "LS" },
                 new sys_common_model(){ name= "Liberia", id= "LR" },
                 new sys_common_model(){ name= "Libyan Arab Jamahiriya", id= "LY" },
                 new sys_common_model(){ name= "Liechtenstein", id= "LI" },
                 new sys_common_model(){ name= "Lithuania", id= "LT" },
                 new sys_common_model(){ name= "Luxembourg", id= "LU" },
                 new sys_common_model(){ name= "Macao", id= "MO" },
                 new sys_common_model(){ name= "Macedonia, The Former Yugoslav Republic of", id= "MK" },
                 new sys_common_model(){ name= "Madagascar", id= "MG" },
                 new sys_common_model(){ name= "Malawi", id= "MW" },
                 new sys_common_model(){ name= "Malaysia", id= "MY" },
                 new sys_common_model(){ name= "Maldives", id= "MV" },
                 new sys_common_model(){ name= "Mali", id= "ML" },
                 new sys_common_model(){ name= "Malta", id= "MT" },
                 new sys_common_model(){ name= "Marshall Islands", id= "MH" },
                 new sys_common_model(){ name= "Martinique", id= "MQ" },
                 new sys_common_model(){ name= "Mauritania", id= "MR" },
                 new sys_common_model(){ name= "Mauritius", id= "MU" },
                 new sys_common_model(){ name= "Mayotte", id= "YT" },
                 new sys_common_model(){ name= "Mexico", id= "MX" },
                 new sys_common_model(){ name= "Micronesia, Federated States of", id= "FM" },
                 new sys_common_model(){ name= "Moldova, Republic of", id= "MD" },
                 new sys_common_model(){ name= "Monaco", id= "MC" },
                 new sys_common_model(){ name= "Mongolia", id= "MN" },
                 new sys_common_model(){ name= "Montenegro", id= "ME" },
                 new sys_common_model(){ name= "Montserrat", id= "MS" },
                 new sys_common_model(){ name= "Morocco", id= "MA" },
                 new sys_common_model(){ name= "Mozambique", id= "MZ" },
                 new sys_common_model(){ name= "Myanmar", id= "MM" },
                 new sys_common_model(){ name= "Namibia", id= "NA" },
                 new sys_common_model(){ name= "Nauru", id= "NR" },
                 new sys_common_model(){ name= "Nepal", id= "NP" },
                 new sys_common_model(){ name= "Netherlands", id= "NL" },
                 new sys_common_model(){ name= "Netherlands Antilles", id= "AN" },
                 new sys_common_model(){ name= "New Caledonia", id= "NC" },
                 new sys_common_model(){ name= "New Zealand", id= "NZ" },
                 new sys_common_model(){ name= "Nicaragua", id= "NI" },
                 new sys_common_model(){ name= "Niger", id= "NE" },
                 new sys_common_model(){ name= "Nigeria", id= "NG" },
                 new sys_common_model(){ name= "Niue", id= "NU" },
                 new sys_common_model(){ name= "Norfolk Island", id= "NF" },
                 new sys_common_model(){ name= "Northern Mariana Islands", id= "MP" },
                 new sys_common_model(){ name= "Norway", id= "NO" },
                 new sys_common_model(){ name= "Oman", id= "OM" },
                 new sys_common_model(){ name= "Pakistan", id= "PK" },
                 new sys_common_model(){ name= "Palau", id= "PW" },
                 new sys_common_model(){ name= "Palestinian Territory, Occupied", id= "PS" },
                 new sys_common_model(){ name= "Panama", id= "PA" },
                 new sys_common_model(){ name= "Papua New Guinea", id= "PG" },
                 new sys_common_model(){ name= "Paraguay", id= "PY" },
                 new sys_common_model(){ name= "Peru", id= "PE" },
                 new sys_common_model(){ name= "Philippines", id= "PH" },
                 new sys_common_model(){ name= "Pitcairn", id= "PN" },
                 new sys_common_model(){ name= "Poland", id= "PL" },
                 new sys_common_model(){ name= "Portugal", id= "PT" },
                 new sys_common_model(){ name= "Puerto Rico", id= "PR" },
                 new sys_common_model(){ name= "Qatar", id= "QA" },
                 new sys_common_model(){ name= "Reunion", id= "RE" },
                 new sys_common_model(){ name= "Romania", id= "RO" },
                 new sys_common_model(){ name= "Russian Federation", id= "RU" },
                 new sys_common_model(){ name= "RWANDA", id= "RW" },
                 new sys_common_model(){ name= "Saint Helena", id= "SH" },
                 new sys_common_model(){ name= "Saint Kitts and Nevis", id= "KN" },
                 new sys_common_model(){ name= "Saint Lucia", id= "LC" },
                 new sys_common_model(){ name= "Saint Pierre and Miquelon", id= "PM" },
                 new sys_common_model(){ name= "Saint Vincent and the Grenadines", id= "VC" },
                 new sys_common_model(){ name= "Samoa", id= "WS" },
                 new sys_common_model(){ name= "San Marino", id= "SM" },
                 new sys_common_model(){ name= "Sao Tome and Principe", id= "ST" },
                 new sys_common_model(){ name= "Saudi Arabia", id= "SA" },
                 new sys_common_model(){ name= "Senegal", id= "SN" },
                 new sys_common_model(){ name= "Serbia", id= "RS" },
                 new sys_common_model(){ name= "Seychelles", id= "SC" },
                 new sys_common_model(){ name= "Sierra Leone", id= "SL" },
                 new sys_common_model(){ name= "Singapore", id= "SG" },
                 new sys_common_model(){ name= "Slovakia", id= "SK" },
                 new sys_common_model(){ name= "Slovenia", id= "SI" },
                 new sys_common_model(){ name= "Solomon Islands", id= "SB" },
                 new sys_common_model(){ name= "Somalia", id= "SO" },
                 new sys_common_model(){ name= "South Africa", id= "ZA" },
                 new sys_common_model(){ name= "South Georgia and the South Sandwich Islands", id= "GS" },
                 new sys_common_model(){ name= "Spain", id= "ES" },
                 new sys_common_model(){ name= "Sri Lanka", id= "LK" },
                 new sys_common_model(){ name= "Sudan", id= "SD" },
                 new sys_common_model(){ name= "Suriname", id= "SR" },
                 new sys_common_model(){ name= "Svalbard and Jan Mayen", id= "SJ" },
                 new sys_common_model(){ name= "Swaziland", id= "SZ" },
                 new sys_common_model(){ name= "Sweden", id= "SE" },
                 new sys_common_model(){ name= "Switzerland", id= "CH" },
                 new sys_common_model(){ name= "Syrian Arab Republic", id= "SY" },
                 new sys_common_model(){ name= "Taiwan, Province of China", id= "TW" },
                 new sys_common_model(){ name= "Tajikistan", id= "TJ" },
                 new sys_common_model(){ name= "Tanzania, United Republic of", id= "TZ" },
                 new sys_common_model(){ name= "Thailand", id= "TH" },
                 new sys_common_model(){ name= "Timor-Leste", id= "TL" },
                 new sys_common_model(){ name= "Togo", id= "TG" },
                 new sys_common_model(){ name= "Tokelau", id= "TK" },
                 new sys_common_model(){ name= "Tonga", id= "TO" },
                 new sys_common_model(){ name= "Trinidad and Tobago", id= "TT" },
                 new sys_common_model(){ name= "Tunisia", id= "TN" },
                 new sys_common_model(){ name= "Turkey", id= "TR" },
                 new sys_common_model(){ name= "Turkmenistan", id= "TM" },
                 new sys_common_model(){ name= "Turks and Caicos Islands", id= "TC" },
                 new sys_common_model(){ name= "Tuvalu", id= "TV" },
                 new sys_common_model(){ name= "Uganda", id= "UG" },
                 new sys_common_model(){ name= "Ukraine", id= "UA" },
                 new sys_common_model(){ name= "United Arab Emirates", id= "AE" },
                 new sys_common_model(){ name= "United Kingdom", id= "GB" },
                 new sys_common_model(){ name= "United States", id= "US" },
                 new sys_common_model(){ name= "United States Minor Outlying Islands", id= "UM" },
                 new sys_common_model(){ name= "Uruguay", id= "UY" },
                 new sys_common_model(){ name= "Uzbekistan", id= "UZ" },
                 new sys_common_model(){ name= "Vanuatu", id= "VU" },
                 new sys_common_model(){ name= "Venezuela", id= "VE" },
                 new sys_common_model(){ name= "Viet Nam", id= "VN" },
                 new sys_common_model(){ name= "Virgin Islands, British", id= "VG" },
                 new sys_common_model(){ name= "Virgin Islands, U.S.", id= "VI" },
                 new sys_common_model(){ name= "Wallis and Futuna", id= "WF" },
                 new sys_common_model(){ name= "Western Sahara", id= "EH" },
                 new sys_common_model(){ name= "Yemen", id= "YE" },
                 new sys_common_model(){ name= "Zambia", id= "ZM" },
                 new sys_common_model(){ name= "Zimbabwe", id= "ZW" }
               };

    }
}